version: '3.8'
services:
    app:
        build: .
        container_name: spring-websocket-app
        ports:
            - "8080:8080"
        depends_on:
            - redis
            - postgres
            - kafka
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/webtoonmaker
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: secret
            SPRING_REDIS_HOST: redis
            SPRING_REDIS_PORT: 6379
            SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
        networks:
            - backend-network

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - backend-network

    postgres:
        image: postgres:16
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: webtoonmaker
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        networks:
            - backend-network

    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
        networks:
            - backend-network

    kafka:
        image: confluentinc/cp-kafka:latest
        container_name: kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        depends_on:
            - zookeeper
        networks:
            - backend-network

networks:
    backend-network:
        name: backend-network
        driver: bridge