spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/aiwebtoonmaker
        username: aiwebtoonmaker
        password: aiwebtoonmaker
    jpa:
        hibernate:
            ddl-auto: create
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true
    mongodb:
        uri: mongodb://localhost:27017/webtoonmaker-chat
    data:
        redis:
            host: redis
            port: 6379
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: chat-consumer
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    websocket:
        broker:
            enabled: true
service:
    jwt:
        secret-key: "7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg=="
        expiration-time: 3600000